spring.application.name=vyakhyanLite


#Local :-
server.port=2026
spring.datasource.url=jdbc:postgresql://localhost:5432/vyakhyan_lite
spring.datasource.username=postgres
spring.datasource.password=Onkar@123
python.api.base-url=https://lite.vyakhyan.com/poirot
##file.upload.base-path= C:/Users/Vaibhav/Downloads/vyakhyanLite_Folder

#Server :-
#server.port=2024
#spring.datasource.url=jdbc:postgresql://localhost:5432/vyakhyan_lite
#spring.datasource.username=postgres
#spring.datasource.password=tatva_wp
#python.api.base-url=https://lite.vyakhyan.com/poirot
##file.upload.base-path= C:/Users/Vaibhav/Downloads/vyakhyanLite_Folder



spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
